version: '3.9'

services:
  golang-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workdir
    tty: true
    ports:
      - 8080:8080

  db:
    image: mysql:latest
    volumes:
        - ./mysql:/var/lib/mysql
    command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'
    container_name: db
    ports:
      - 3306:3306

  adminer:
    container_name: adminer-for-go
    image: adminer
    depends_on:
      - db
    ports:
      - 8090:8080
      
volumes:
  db-volume:
